name: "AI Secure Code Review"
description: "Run a 2-minute AppSec code review on changed PR hunks using a ChatGPT-compatible API, with GitLeaks secret scanning."
author: "DevSecOps-AppSec"
branding:
  icon: "shield"
  color: "blue"

inputs:
  openai_api_key:
    description: "API key for OpenAI or compatible provider"
    required: true
  model:
    description: "Model name"
    required: false
    default: "gpt-4o-mini"
  max_tokens:
    description: "Max output tokens"
    required: false
    default: "1200"
  time_budget_seconds:
    description: "Time budget for analysis"
    required: false
    default: "100"
  max_files:
    description: "Max changed files to review"
    required: false
    default: "30"
  max_lines:
    description: "Max changed lines across files"
    required: false
    default: "1200"
  line_trim_per_file:
    description: "Per-file hunk line cap"
    required: false
    default: "300"
  risky_exts:
    description: "Comma-separated file extensions"
    required: false
    default: "js,ts,tsx,jsx,py,go,rb,php,java,kt,cs,rs,swift,c,cc,cpp,h,sql,sh,ps1,yml,yaml,json,html,htm,css,scss,vue,mdx"
  openai_base_url:
    description: "Optional: alternate base URL (e.g., OpenRouter)"
    required: false
    default: ""
  openai_org:
    description: "Optional: OpenAI org id header"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # ---- Install GitLeaks manually ----
    - name: Install GitLeaks
      shell: bash
      env:
        GITLEAKS_VERSION: "8.24.3"
      run: |
        set -euo pipefail
        curl -sSL -o /tmp/gitleaks.tar.gz \
          "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
        tar -xzf /tmp/gitleaks.tar.gz -C /tmp
        sudo mv /tmp/gitleaks /usr/local/bin/gitleaks
        gitleaks version

    # ---- Run GitLeaks on the PR commit range ----
    - name: Detect secrets with GitLeaks
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        BASE_SHA=$(jq -r '.pull_request.base.sha' "$GITHUB_EVENT_PATH")
        HEAD_SHA=$(jq -r '.pull_request.head.sha' "$GITHUB_EVENT_PATH")
        gitleaks detect \
          --redact \
          --source "${{ github.workspace }}" \
          --log-opts="--no-merges --first-parent ${BASE_SHA}..${HEAD_SHA}" \
          --report-format json \
          --report-path "${{ github.workspace }}/gitleaks-report.json" || true
        test -f "${{ github.workspace }}/gitleaks-report.json" || echo "[]" > "${{ github.workspace }}/gitleaks-report.json"

    # ---- Fallback for non-PR events ----
    - name: Detect secrets with GitLeaks (working tree)
      if: ${{ github.event_name != 'pull_request' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        gitleaks detect \
          --redact \
          --no-git \
          --source "${{ github.workspace }}" \
          --report-format json \
          --report-path "${{ github.workspace }}/gitleaks-report.json" || true
        test -f "${{ github.workspace }}/gitleaks-report.json" || echo "[]" > "${{ github.workspace }}/gitleaks-report.json"

    - name: Show GitLeaks findings (optional)
      if: always()
      shell: bash
      run: |
        head -c 20000 "${{ github.workspace }}/gitleaks-report.json" || true

    - name: Install deps
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci --ignore-scripts --no-audit --fund=false || npm i

    - name: Run secure review
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        OPENAI_BASE_URL: ${{ inputs.openai_base_url }}
        OPENAI_ORG: ${{ inputs.openai_org }}
        MODEL: ${{ inputs.model }}
        MAX_TOKENS: ${{ inputs.max_tokens }}
        TIME_BUDGET_SECONDS: ${{ inputs.time_budget_seconds }}
        MAX_FILES: ${{ inputs.max_files }}
        MAX_LINES: ${{ inputs.max_lines }}
        LINE_TRIM_PER_FILE: ${{ inputs.line_trim_per_file }}
        RISKY_EXTS: ${{ inputs.risky_exts }}
      run: node review_pr.js
