name: "AI Secure Code Review"
description: "Run a 2-minute AppSec code review on changed PR hunks using a ChatGPT-compatible API, with GitLeaks secret scanning."
author: "DevSecOps-AppSec"
branding:
  icon: "shield"
  color: "blue"

inputs:
  openai_api_key:
    description: "API key for OpenAI or compatible provider"
    required: true
  model:
    description: "Model name"
    required: false
    default: "gpt-4o-mini"
  max_tokens:
    description: "Max output tokens"
    required: false
    default: "1200"
  time_budget_seconds:
    description: "Time budget for analysis"
    required: false
    default: "100"
  max_files:
    description: "Max changed files to review"
    required: false
    default: "30"
  max_lines:
    description: "Max changed lines across files"
    required: false
    default: "1200"
  line_trim_per_file:
    description: "Per-file hunk line cap"
    required: false
    default: "300"
  risky_exts:
    description: "Comma-separated file extensions"
    required: false
    default: "js,ts,tsx,jsx,py,go,rb,php,java,kt,cs,rs,swift,c,cc,cpp,h,sql,sh,ps1,yml,yaml,json,html,htm,css,scss,vue,mdx"
  openai_base_url:
    description: "Optional: alternate base URL (e.g., OpenRouter)"
    required: false
    default: ""
  openai_org:
    description: "Optional: OpenAI org id header"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # --- Use the official GitLeaks Action (scans repo, writes SARIF) ---
    - name: Run GitLeaks scan
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        version: latest
      continue-on-error: true  # don't fail the job; we'll surface findings in our PR comment

    # Convert GitLeaks SARIF (results.sarif) -> simple JSON array (gitleaks-report.json)
    - name: Convert GitLeaks SARIF to JSON
      shell: bash
      run: |
        set -euo pipefail
        if [ -f "results.sarif" ]; then
          # Extract file, line, ruleId into a flat array the JS expects
          jq '
            (.runs[0].results // []) |
            map({
              File: ( .locations[0].physicalLocation.artifactLocation.uri // "unknown"),
              StartLine: ( .locations[0].physicalLocation.region.startLine // 0),
              RuleID: ( .ruleId // "gitleaks" )
            })
          ' results.sarif > gitleaks-report.json
        else
          echo "[]" > gitleaks-report.json
        fi

    - name: Show GitLeaks findings (optional)
      if: always()
      shell: bash
      run: |
        echo "GitLeaks JSON summary (first 20KB):"
        head -c 20000 gitleaks-report.json || true

    - name: Install deps
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci --ignore-scripts --no-audit --fund=false || npm i

    - name: Run secure review
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        OPENAI_BASE_URL: ${{ inputs.openai_base_url }}
        OPENAI_ORG: ${{ inputs.openai_org }}
        MODEL: ${{ inputs.model }}
        MAX_TOKENS: ${{ inputs.max_tokens }}
        TIME_BUDGET_SECONDS: ${{ inputs.time_budget_seconds }}
        MAX_FILES: ${{ inputs.max_files }}
        MAX_LINES: ${{ inputs.max_lines }}
        LINE_TRIM_PER_FILE: ${{ inputs.line_trim_per_file }}
        RISKY_EXTS: ${{ inputs.risky_exts }}
      run: node review_pr.js
